### ISSUE TITLE
Add french keymap

### ISSUE THREAD

**Issue by boris-sbizzera** [KinesisCorporation/Adv360-Pro-ZMK#102]
It seams that i can't use azerty default keymap (french layout).
any suggestions?
thank you

**Comment by KinesisCorporation** [comment]
Hi Boris, 

The Advantage360 is a not a standard keyboard layout so its not as simple as just enabling AZERTY in your OS. But you can re-assign keys to perform any supported action in any layer.

**Comment by boris-sbizzera** [comment]
so how can i assign for example the key "é" to be on Num_2 space on querty? (i can't find the key on the zmk gui provided)
Thank you

**Comment by KinesisCorporation** [comment]
Here is the list of supported key codes:

https://zmk.dev/docs/codes

**Comment by boris-sbizzera** [comment]
so I can't create an azerty layout?

**Comment by boris-sbizzera** [comment]
I can't add this layout

![KB600-FR-710x532-flag](https://user-images.githubusercontent.com/17552720/218814843-25ebd465-7245-4537-816b-776a0e927368.jpg)

**Comment by ReFil** [comment]
You should set it up as a normal qwerty then configure your operating system in azerty mode

**Comment by boris-sbizzera** [comment]
thanks for your help!

**Comment by sieman** [comment]
Thanks for this issue. I'm looking for a solution for a german layout (especially neo-layout.org).
