### ISSUE TITLE
Startup LED is too bright

### ISSUE THREAD

**Issue by z0al** [KinesisCorporation/Adv360-Pro-ZMK#129]
I have to cover it with my hand otherwise it hurts my eyes. Demo below :) 

https://user-images.githubusercontent.com/12673605/229476784-bc7d2fd5-f1d3-49b9-bc8c-631f43e7b944.mp4

I would appreciate any guidance on how to change the brightness. Thanks

**Comment by KinesisCorporation** [comment]
Hi there! It's hard to tell anything conclusively from the video. You can try re-configuring the backlighting using the instructions at the top of page 14 in the User Manual linked below but that may not solve the problem:

https://kinesis-ergo.com/wp-content/uploads/Advantage360-ZMK-KB360-PRO-Users-Manual-v3-10-23.pdf

Failing that, please submit a trouble ticket and we can issue an RMA for a repair:

https://kinesis-ergo.com/support/contact-a-technician/
