### ISSUE TITLE
Build failing using make (windows using WSL2 and docker)

### ISSUE THREAD

**Issue by Arethusag** [KinesisCorporation/Adv360-Pro-ZMK#140]
Running the make command gives the following error:

`/usr/bin/env: 'bash\r': No such file or directory
make: *** [Makefile:16: all] Error 127`

**Comment by ReFil** [comment]
I've followed all the setup commands as per the readme and i cannot replicate this issue on WSL2 Ubuntu 20.04. What WSL distro are you using?

**Comment by Arethusag** [comment]
Thanks for the quick response. I am a novice but i suspect that the error is related to the  SELINUX1 and SELINUX2 variables in the Makefile.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

The docker run command ion the makefile is what is giving me the error: 

```
/usr/bin/docker run --rm -it --name zmk \
        -v /mnt/c/*REPOPATH/Adv360-Pro-ZMK/firmware:/app/firmware:z \
        -v /mnt/c/*REPOPATH*/Adv360-Pro-ZMK/config:/app/config:ro,z \
        -e TIMESTAMP=20230416161412 \
        zmk
```

**Comment by ReFil** [comment]
the SELinux variables should not be causing a problem, it's only for Macs as they do not support docker SELinux

**Comment by ReFil** [comment]
I suspect windows style line endings is configured on git, these will add extra characters into the files that the WSL subsystem cannot handle

**Comment by ReFil** [comment]
A solution would be to run these commands in the folder where the adv360 files are contained
`sudo apt-get install -y dos2unix # Installs dos2unix Linux`  
`sudo find . -type f -exec dos2unix {} \; # recursively removes windows related stuff`

**Comment by Arethusag** [comment]
This resolved the issue with make. Also, cloning the repo from within WSL circumvented the issue entirely.

> A solution would be to run these commands in the folder where the adv360 files are contained `sudo apt-get install -y dos2unix # Installs dos2unix Linux` `sudo find . -type f -exec dos2unix {} \; # recursively removes windows related stuff`

Thank-you!
