### ISSUE TITLE
CONFIG_ZMK_RGB_UNDERGLOW_ON_START does not work.

### ISSUE THREAD

**Issue by moon0326** [KinesisCorporation/Adv360-Pro-ZMK#143]
Hi,

I'm trying to turn off the led indicators on startup. 

Looking at the ZMK documentation, `CONFIG_ZMK_RGB_UNDERGLOW_ON_START` is the correct value.

I tried setting `CONFIG_ZMK_RGB_UNDERGLOW_ON_START` to `n`, but it did not work.

Am I changing the correct config value for Adv 360 pro?

**Comment by ReFil** [comment]
~~This is only for the RGB behaviour when the board is first initialised, after that the lighting values are stored in the flash memory. If you want the lighting to be off all you need to do is use the RGB toggle key command in the manual, then wait for a minute for the changes to be saved to flash, after that powering on and off the keyboard halves the lights should remain off~~ this isn't quite accurate, brightness and "effect" are saved but on state is overriden

**Comment by moon0326** [comment]
> 

Thanks. It still turns on when I turn off and on the keyboard halves.

Just to clarify, I'm trying to turn off the 6 led indicators, not the backlights.

**Comment by ReFil** [comment]
how long did you leave it after turning off the indicator lights? There's a period in which changes are not saved to the flash memory in order to prevent flash wear

**Comment by moon0326** [comment]
> how long did you leave it after turning off the indicator lights? There's a period in which changes are not saved to the flash memory in order to prevent flash wear

I made sure to wait for 5 mins. The led indicator under the user icon turns on.

**Comment by ReFil** [comment]
I've investigated and found the bug causing the behaviour you mention, it will be patched soon

**Comment by ReFil** [comment]
This problem should now be fixed in this commit https://github.com/ReFil/zmk/commit/dea3e81154d981ec067ae26c9edb5edf56971929

If you could test and confirm that would be much appreciated

**Comment by moon0326** [comment]
Thank you for the quick fix!

It's working well 👍

**Comment by hwangdylan** [comment]
@ReFil how can I get the latest updates into my keyboard? I tried to rebuild my fork and reflashed but it didn't include the newest changes from your commit. Matter of fact I can't find that commit in the official zmk firmware. What am i missing here?

**Comment by hwangdylan** [comment]
oh so i can see that when i build I get the latest commit but it seems like the light still turns on after a reboot. From the above comments it seems like i do not need to make any changes to CONFIG_ZMK_RGB_UNDERGLOW_ON_START and it should still work

**Comment by moon0326** [comment]
Hi @ReFil 

This issue is occurring in v3 version again.

I flashed V3 version last week and noticed the same issue again.

Steps to reproduce:

1. Turn on the indicator (in my case, it's the 2nd light on the left half)
2. Turn it off by MOD + backspace
3. Wait for 5 mins
4. Turn off the both halves
5. Turn on the both halves
6. The led indicator is on again

**Comment by ReFil** [comment]
That's really strange because the fix was brought forwards to v3, I will investigate further when i have the time

**Comment by moon0326** [comment]
@ReFil Any updates?

**Comment by ReFil** [comment]
i'm sorry i cant replicate this, the config option works properly for me using the latest version of this config repository

**Comment by moon0326** [comment]
@ReFil Thanks for looking into it.

It now works as expected after flashing `Adv360 Pro Settings Reset Flash Erase` firmware.
