### ISSUE TITLE
FN (Global) Modifier

### ISSUE THREAD

**Issue by sieman** [KinesisCorporation/Adv360-Pro-ZMK#147]
I like to have the FN key as modifier. Because I have many key binding in Code Editors that i can now not use any more.

**Comment by ReFil** [comment]
Hi, sorry what do you mean by this? all keys on the 360 pro are remappable to anything you want

**Comment by sieman** [comment]
Hi, thanks for the answer. I'm using Mac Os. I launched Karabiner-EventViewer (Karabiner Elements) or Keyboard Viewer (Mac Os). If I press the FN Key on the MacBook Pro Keyboard it produces an event that is displayed in the keyboard viewer.
If I press the fn on the 360pro no event is displayed. How to remap a key that produce a fn event? Or which is the right setting in https://kinesiscorporation.github.io/Adv360-Pro-GUI/

**Comment by ReFil** [comment]
Apple FN key does not have a keycode associated with it in ZMK because it's a unique implementation, unfortunately you'll need to find a different way to trigger your keybindings

**Comment by sieman** [comment]
The FN key can also be found on notebook keyboards from other manufacturers. The FN key is not unique to Apple but common.

**Comment by ReFil** [comment]
The Apple implementation of the FN key is unique

**Comment by sieman** [comment]
Do you see a approuch to make a common FN key event, that is not apple specific?

**Comment by ReFil** [comment]
No, apple use additional HID pages and it's not intercompatible with any other fn key implementation

**Comment by sieman** [comment]
Okay how to make the other fn key implementation?

**Comment by ReFil** [comment]
This is vendor and device dependent, there's no one size fits all solution

**Comment by KinesisCorporation** [comment]
Think of it this way, lots of keys are called "Fn" but they have no relationship to each other.
