### ISSUE TITLE
Turn off Bluetooth 

### ISSUE THREAD

**Issue by sieman** [KinesisCorporation/Adv360-Pro-ZMK#148]
I using the Advantage360 Professional via USB wires and i have turn off bluetooth in MacOs. The Keyboard works well but the Bluetooth is still active on the keyboard. How to deactivate the bluetooth on the keyboard?

**Comment by ReFil** [comment]
The bluetooth has to be active at all times because it's how the halves communicate

**Comment by sieman** [comment]
Thanks for the answer. Then should the halves communicate via usb. Maybe it is some day possible.

**Comment by craftyguy** [comment]
I might be mistaken, but it seems like the keyboard is always in pairing mode when connected to a computer over usb. If that's true, it seems like a bad idea if anyone nearby can connect to it. At the very least, it shouldn't be advertising itself all the time? Is there a way to disable pairing mode when usb is connected to a system?

**Comment by ReFil** [comment]
It always prioritises the USB connection so even if the pairing slot is empty and someone pairs no data can be retrieved. Furthermore it's not pairable once the slot has been connected to. There is a passkey pairing mode for setups that require more security, it can be enabled in the config

**Comment by craftyguy** [comment]
what happens in this scenario:

1) usb is disconnected

2) someone else pairs with the keyboard over BT

3) usb connection is re-established (or perhaps the user thinks it is?) and they go to enter a password or something to unlock their system

Anyways, I have 0 interest in connecting this keyboard to a computer over bluetooth, so a way to just straight up disable pairing at all would be ideal, even if it's in the config. It would eliminate all sorts of "what if" scenarios about where data from the keyboard is being sent. I guess setting a passphrase would kinda do that, though it could be brute forced?

**Comment by ReFil** [comment]
As soon as usb connection is re-established data goes out that way. There's a visual indication of Bluetooth connection through the status LEDs. It's also not possible to brute force the passkey as it's entered dynamically on the keys during the pairing sequence and will timeout. 

Disabling Bluetooth will disable the connection between the halves unfortunately. There's no scope to have Bluetooth available only between the two halves within the current code framework. There is a pull request currently open pending testing in the base adv360z3.2 repo to disable Bluetooth advertising under certain circumstances

**Comment by sieman** [comment]
![IMG_6329](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/3419376/0eccd85f-ba73-4024-a047-4cc20b323c09)

I did a RF measurement with [The AC2 Acousticom](https://www.emfields-solutions.com/products/ac2-acousticom-2.asp) so in the picture you can see the result. 

Hopefully you find a solution to synchronise the two halfes via usb and turn off Bluetooth in the next versions (adv360z3.2).

**Comment by aaronjensen** [comment]
@ReFil did the PR for disabling advertising ever get merged? I'm in a similar situation as OP and would like to turn BT advertising off entirely.

**Comment by ReFil** [comment]
Hi @aaronjensen  unfortunately it didnt, it hooked into quite a few core functions and would have made maintaining the 360 Pro quite tricky. I might look into doing it at some point in a way that is easily maintainable
