### ISSUE TITLE
GUI doesn't work with my fork of the adv360 zmk repo

### ISSUE THREAD

**Issue by sarahspak** [KinesisCorporation/Adv360-Pro-ZMK#153]
I forked this repo, added a new macro manually to https://github.com/sarahspak/Adv360-Pro-ZMK/blob/V2.0/config/macros.dtsi, and now the GUI doesn't load anything (just hangs and shows a blank screen).  

the web editor worked fine before my change (adding the macro manually). Is there anything I can do to get the web GUI working again?

**Comment by ReFil** [comment]
have you tried removing that macro and adding it through the GUI?

**Comment by ReFil** [comment]
Just following up on this, have you been able to work around the issue?

**Comment by KinesisCorporation** [comment]
Looks like there was an error in the macro you wrote. You added a carriage return at the end of line 5 and line 6, they should have been all on the same line.
