### ISSUE TITLE
Update bin/build.sh to support local builds

### ISSUE THREAD

**Issue by zemackdaddy** [KinesisCorporation/Adv360-Pro-ZMK#16]
I noticed that you deleted lines in .github/workflows/build.yml but not in bin/build.sh.

I can build locally (mac) and the left firmware is in the zephyr folder but not as the name in bin/build.sh without removing the "matching" lines in bin/build.  But the contents of the build/left/zephyr folder are that of my left build.

Doesn't it make sense to remove it in that file as well?

`#!/usr/bin/env bash

set -e

PWD=$(pwd)
TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")

\# West Build (left)
west build -s zmk/app -d build/left -b adv360_left -- -DZMK_CONFIG="${PWD}/config"
\# Adv360 Left DTS File
\# remove this cat -n build/left/zephyr/adv360_left.dts.pre.tmp
\# Adv360 Left Kconfig file
cat build/left/zephyr/.config | grep -v "^#" | grep -v "^$"
\# West Build (right)
west build -s zmk/app -d build/right -b adv360_right -- -DZMK_CONFIG="${PWD}/config"
\# Adv360 Right DTS File
\# remove this cat -n build/right/zephyr/adv360_right.dts.pre.tmp
\# Adv360 Right Kconfig file
cat build/right/zephyr/.config | grep -v "^#" | grep -v "^$"
\# Rename zmk.uf2
cp build/left/zephyr/zmk.uf2 ./firmware/${TIMESTAMP}-left.uf2 && cp build/right/zephyr/zmk.uf2 ./firmware/${TIMESTAMP}-right.uf2
`

**Comment by ReFil** [comment]
Which branch are you using?

**Comment by zemackdaddy** [comment]
I am sorry I conflated two things here.  This issue should be in a different repo, referencing this new commit.

**Comment by zemackdaddy** [comment]
[V2-beta](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/tree/V2.0-beta)

This references the paths you removed in [.github/workflows/build.yml](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V2.0-beta/bin/build.sh)

**Comment by zemackdaddy** [comment]
updated my original comment above.  Apologies.  This is all a bit new.

**Comment by zemackdaddy** [comment]
[My repo](https://github.com/zemackdaddy/Adv360-Pro-ZMK/tree/V2.0-beta)

For context, I split setup.sh into two files.  I also split Dockerfile. 
I modified the process so that I run a setup–zmk.sh to prepare the base image.
I then run setup-build.sh followed by run-local.sh to pull in my local changes and build locally.

The important part is that run-local.sh if I don't comment out the same cat statements you removed in the yaml file [here](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V2.0-beta/.github/workflows/build.yml).

My local build will fail in the same manner if I just run setup.sh and run.sh.

So since you modified a file that removes the cat statements, I thought maybe they should also be removed in the build script?

**Comment by ReFil** [comment]
Ah I understand now. Yes, that makes sense now. My apologies I didn't do the local building stuff. Will make those fixes asap, thank you for bringing this to my attention

**Comment by zemackdaddy** [comment]
I'm glad I saw your changes.  I was stumped!

**Comment by ReFil** [comment]
Closing as has been fixed
