### ISSUE TITLE
V3.0-beta doesn’t work

### ISSUE THREAD

**Issue by ebzzry** [KinesisCorporation/Adv360-Pro-ZMK#164]
The branch V3.0-beta doesn’t work at all with me. After flashing the keyboard, the middle left LED on the left half would keep blinking, white the right half doesn’t have any blinking LEDs, at all.

I reverted back to the V2.0 branch.

**Comment by ReFil** [comment]
Did you perform a settings reset prior to upgrading? The lights on the right side should slow flash red until connecting. Middle led on left side flashing is normal behaviour. Did you try pressing the mod key (top left key on right side board)? This should illuminate an led green on both sides

**Comment by ebzzry** [comment]
Yes, I did all of that.

**Comment by ReFil** [comment]
Does the green led illuminate on both sides when you hold the mod key down?

**Comment by ebzzry** [comment]
Prior to flashing, yes. After flashing, not anymore.

The procedure that I used was the same one that I have been using with V2.0.

**Comment by ReFil** [comment]
If you connect the left side to the computer over USB do keys work?

**Comment by ebzzry** [comment]
It won’t work, at all. So, what I did to reflash it back to V2.0 was to use the pins.

**Comment by ReFil** [comment]
Are you using the default keymap? Did you use the settings reset file in the V3.0 beta branch as it was updated as part of the upgrade?

**Comment by michaelglass** [comment]
I had @ebzzry's experience until I used [the reset file.](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/raw/V3.0-beta/settings-reset.uf2) (thanks @ReFil !)

**Comment by ebzzry** [comment]
Let me do that.

**Comment by ReFil** [comment]
Just following up, @ebzzry have you had the opportunity to do this yet?

**Comment by ReFil** [comment]
Has resetting with the correct file yielded any change?

**Comment by ebzzry** [comment]
After using the reset file, I was able to successfully flash the V3.0-beta firmware! Thanks!
