### ISSUE TITLE
Merge conflict with new firmware update

### ISSUE THREAD

**Issue by vseehausen** [KinesisCorporation/Adv360-Pro-ZMK#167]
Hey,

when I try to merge your firmware update, I get merge conflicts.

I would not like to re-create all my key mappings. Also, I don't know how to resolve the merge conflicts. 

I think the best solution would be to add a default keymapping file and a custom key mapping file, so your users can easily merge the firmware update. 

Also, please understand that I don't want to spend 2 days understanding what goes on in the code. I bought this keyboard for 649 and I expect it to work, and don't have Bluetooth issues or needed maintenance code work. It is a keyboard, not an arduino or so. :)

Here is the PR with the merge conflicts: https://github.com/Valentin-Seehausen/Adv360-Pro-ZMK/pull/3

Thanks!

**Comment by michaelglass** [comment]
~~I _believe_ with those merge conflicts, you can just choose your own diff and ignore the files in the 3.0 branch.~~ WHOOPS

**Comment by ReFil** [comment]
The update removes 8 "&none" entries from each layer in the adv360.keymap and keymap.json, choosing your own diff will result in keys being shifted across.

you can see in the diff where the entries are removed, just remove them from your own keymap in each layer and it will work
https://github.com/Valentin-Seehausen/Adv360-Pro-ZMK/pull/3/files#diff-df49145a9e31146b8135f11531a1734a3ec03e1340e9eb6a9016cbb39aea7308

**Comment by ReFil** [comment]
![image](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/31960031/b9d696e0-6c6b-4f2c-a95e-85458b6ffb0e)
here are the &none entries that need removing in adv360.keymap

**Comment by vseehausen** [comment]
Ok so I basically accept all your diffs and none of mine?

Thanks for the prompt reply. Have to say support is amazing.

**Comment by vseehausen** [comment]
@ReFil ?

**Comment by ReFil** [comment]
Apologies, yes if you accept my changes the merge conflicts will be resolved however your custom keymap will not be reserved. The easiest way is probably to screenshot it in the editor and recreate it

**Comment by vseehausen** [comment]
Come on, that is not a solution! This is a high-end product. 

What about the solution I proposed?

**Comment by ReFil** [comment]
An alternative option is removing the unnecessary &none entries in your keymap as i detailed [here](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/167#issuecomment-1580961867)

**Comment by gridlocdev** [comment]
I've put together some ideas in Discussion #170 for how these types of upgrades could be made a bit smoother, since I ran into this as well.

**Comment by vseehausen** [comment]
> The update removes 8 "&none" entries from each layer in the adv360.keymap and keymap.json, choosing your own diff will result in keys being shifted across.
> 
> you can see in the diff where the entries are removed, just remove them from your own keymap in each layer and it will work https://github.com/Valentin-Seehausen/Adv360-Pro-ZMK/pull/3/files#diff-df49145a9e31146b8135f11531a1734a3ec03e1340e9eb6a9016cbb39aea7308

For the records, I removed the &none entries from my file and I now have these merge conflicts: https://github.com/Valentin-Seehausen/Adv360-Pro-ZMK/pull/4

**Comment by ReFil** [comment]
You're attempting to merge in V3.0 beta in that PR. This changes a lot of things and will lead to conflicts. An upgrade guide hasn't been written yet for V3.0, it's not ready for inexperienced users hence why it's still in beta prerelease testing. Please return to merging in V2.0 first

**Comment by vseehausen** [comment]
> You're attempting to merge in V3.0 beta in that PR. This changes a lot of things and will lead to conflicts. An upgrade guide hasn't been written yet for V3.0, it's not ready for inexperienced users hence why it's still in beta prerelease testing. Please return to merging in V2.0 first

But that was the initial idea: https://twitter.com/kinesisergo/status/1664712878124060672

**Comment by ReFil** [comment]
Closing as solved with the addition of instructions to resolve the conflict
