### ISSUE TITLE
Is there a way to control the leds through the keymap config?

### ISSUE THREAD

**Issue by yanshay** [KinesisCorporation/Adv360-Pro-ZMK#187]
Is there a way to turn on/off the leds through config and not using the default behavior?
So for example, if I want to turn on the 'scroll-lock' led when I have some stick key active, is there a way to do that?
I seems to be possible with the backlight, but couldn't find a way to do that with the leds (other than to switch layers and control the layer led).

**Comment by ReFil** [comment]
Unfortunately this isn't possible in the firmware, and isn't a planned feature
