### ISSUE TITLE
v3 update from stock firmware / bricked device?

### ISSUE THREAD

**Issue by prez** [KinesisCorporation/Adv360-Pro-ZMK#201]
I've been using the stock firmware and decided I now want to remap keys.
Flashed the build artifact from my (unchanged) fork of the v3.0 branch and the right half stopped working.
Then flashed [Adv360 Pro Factory Default V3.0 (7-6-23)](https://kinesis-ergo.com/download/advantage360-professional-factory-default-7-6-23/) and now both halves stopped working, right one blinks red. 

How do I recover from this state and how do I now successfully flash v3.0 firmware? Thank you.

**Comment by ReFil** [comment]
Hi, what do you mean by both halves stopped working? Does the left one not work over USB? 

Please flash the v3.0 settings reset from the Kinesis support website to both sides, then flash your firmware

**Comment by prez** [comment]
> Hi, what do you mean by both halves stopped working? Does the left one not work over USB?

Exactly.

> Please flash the v3.0 settings reset from the Kinesis support website to both sides, then flash your firmware

Did that just now (on the left half). The file finished copying a couple of minutes ago, but the left half did not unmount and the three green lights are still on(not blinking). Is this expected? Do I have to unmount manually?

**Comment by ReFil** [comment]
You need to flash it on the right half too. Then reset both boards, then flash the factory firmware onto both halves

**Comment by prez** [comment]
Okay, done. It's now back to factory default and both halves work again over usb. Can I flash the v3.0 build now or is the factory default -> v3.0 update procedure different?

**Comment by ReFil** [comment]
You can upgrade from factory v3.0 to a custom 3.0 based firmware no problem. Have you been able to get the two halves working together over Bluetooth now?

**Comment by prez** [comment]
The upgrade procedure went smoothly and everything works as expected over bluetooth again. 
Thank you for the help, you are amazing!

**Comment by ReFil** [comment]
No worries, happy to be of assistance
