### ISSUE TITLE
Addition of Version History

### ISSUE THREAD

**Issue by patricksalo** [KinesisCorporation/Adv360-Pro-ZMK#214]
Could you please add in version history either to the README.md or a different file in the repo? As it stands right now, without a bit of work, it's really hard to determine what features have changed for a release and whether or not it's worth the effort of compiling firmware and loading it up on my Adv360 Pro. Additionally it might be helpful to provide info as what version of the ZMK firmware each Adv360-Pro release is tied to.

Here's a real world example. I'm currently on 2.x and noticed that there's a new 3.x release. It's really unclear to me if I should move up to 3.x or not, what bugs/features got released and if the effort is worth it, especially with issue #198 - Serious Bluetooth regression being a potential.

**Comment by KinesisCorporation** [comment]
Received with thanks. Let us see what we can do here.
