### ISSUE TITLE
How do I set key repeat?

### ISSUE THREAD

**Issue by mluogh** [KinesisCorporation/Adv360-Pro-ZMK#220]
I would like my keys to repeat, i.e. holding down 'h' should give me "hhhhhhh". 

I don't see a setting for this on the GUI editor.

Thanks.

**Comment by ReFil** [comment]
This isn't a GUI setting, the Adv360 pro should act like any other keyboard when the key is held down, ensure the operating system key repeat settings are appropriately set

**Comment by ReFil** [comment]
Closing issue as unplanned, key repeat settings are not in the scope of the firmware
