### ISSUE TITLE
New Keyboard Today. Cannot connect to MacBook Pro

### ISSUE THREAD

**Issue by PetulantPenguin** [KinesisCorporation/Adv360-Pro-ZMK#224]
I just got the ADV360.

One Adv360 appears in the bluetooth New Devices list.
But, it doesn't connect. I tried restarting the Macbook. But, no change.

Apple M2 Pro
Venture 13.5.2

**Comment by ReFil** [comment]
Have you used the bluetooth clear button? (mod+ right windows)

**Comment by ReFil** [comment]
Just following up on this, are you still encountering issues?

**Comment by PetulantPenguin** [comment]
I did not try that yet. I will try shortly.

I remapped some keys and restarted the keyboard a couple times yesterday and the day before. Bluetooth still didn't connect after that.

**Comment by ReFil** [comment]
Also try connecting it to a smartphone or other device to ensure its functioning correctly

**Comment by PetulantPenguin** [comment]
I connected it to my iphone and it worked.
on my macbook, mostly i see 1 ADvPro in the bluetooth settigns. sometimes (rarely) i see 2 of them.
I click connect next to the device. Sometimes it flips to Disconnect briefly, but then goes back to connect as if nothing had happened. and the keyboard always remains in the new devices section of the bluetooth window

**Comment by ReFil** [comment]
Press mod+2, ensure the profile light is fast flashing and try pairing it to your Mac again

**Comment by PetulantPenguin** [comment]
Fast flashing. Same deal.

**Comment by ReFil** [comment]
https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V3.0/config/boards/arm/adv360/adv360_left_defconfig#L52-L57 try removing these lines on your repo

**Comment by KinesisCorporation** [comment]
> I just got the ADV360.
> 
> One Adv360 appears in the bluetooth New Devices list. But, it doesn't connect. I tried restarting the Macbook. But, no change.
> 
> Apple M2 Pro Venture 13.5.2

Can you provide a screen shot of your Bluetooth menu. On our macOS Ventura MBP we have "My Devices" and "Nearby Devices", but nothing called "New Devices"

**Comment by PetulantPenguin** [comment]
That’s what it is. I’m not at the house right now, but I will send you a screenshot soon.

**Comment by KinesisCorporation** [comment]
@PetulantPenguin 

Any update?

**Comment by KinesisCorporation** [comment]
@PetulantPenguin Bump

**Comment by PetulantPenguin** [comment]
sorry. i took a trip across the country. will be back with time to try it tomorrow.

thanks for keeping with me.

**Comment by KinesisCorporation** [comment]
We will close this issue unless we hear back soon. Thanks!

**Comment by ReFil** [comment]
Hello, just following up on this, please try the latest update as it has several improvements to help with host connections, if we dont hear back within 48 hours we will consider this issue stale and close as such
