### ISSUE TITLE
Updating from v2 to v3

### ISSUE THREAD

**Issue by 0xfourzerofour** [KinesisCorporation/Adv360-Pro-ZMK#228]
I followed the instructions and was able to update the left side, but when I try to go to the right side and press mod + macro3 nothing happens and it cannot connect

**Comment by KinesisCorporation** [comment]
Try using a paperclip to a double-click the bootloader button on the right side. That is the preferred way to open the drives because the left and right side lose connection during some resets/updates.

**Comment by 0xfourzerofour** [comment]
thank you that fixed the issue I was able to upgrade and connect fine now
