### ISSUE TITLE
Entire column of keys not working Fn, Shift, Esc, Tab, Plus/Equals.

### ISSUE THREAD

**Issue by rustyconover** [KinesisCorporation/Adv360-Pro-ZMK#239]
Hello, I've loved my Advantage 360 ZMK keyboard so far, but today an entire column of keys stopped working. 

I use firmware version 3.0, but my: Fn, Shift, Esc, Tab, Plus/Equals (can't type it) no longer respond to keypresses.  I'm using Ventura 13.5.2.

Even when I press the fn key the LED no longer changes color.

All over keys work perfectly.

Please advise if there is some software change to be made or this has been seen before.

**Comment by ReFil** [comment]
This sounds like a hardware issue. Please open a ticket with Kinesis support on the website. https://kinesis-ergo.com/support/kb360pro/#ticket

**Comment by ReFil** [comment]
Just following up on this, have you had this issue sorted?

**Comment by KinesisCorporation** [comment]
@rustyconover We have received your ticket and will handle your RMA directly. Sorry for the inconvenience.
