### ISSUE TITLE
Add GLOBE to keymap

### ISSUE THREAD

**Issue by davidmondok** [KinesisCorporation/Adv360-Pro-ZMK#240]
Whenever I assign `GLOBE` to a key the `make` command fails with this error message:
```
CMake Error at /app/zephyr/cmake/modules/dts.cmake:230 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /app/zephyr/cmake/modules/zephyr_default.cmake:108 (include)
  /app/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /app/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:15 (find_package)
```

`GLOBE` would be the special `fn` key on a Mac keyboard that I'm trying to setup with my new Advantage360 Pro. Adv360-Pro-GUI doesn't offer `GLOBE`, as a choice so I used https://nickcoutsos.github.io/keymap-editor/, which honestly, is simply the better editor due to including modifiers. But I also edited a working keymap myself to make sure, the editor wasn't causing the problem and got the same error.

**Comment by ReFil** [comment]
Globe key is not currently implemented on the 360 pro and will be brought in with the next minor update when it happens. There are workarounds to implement the globe key, see [this issue](https://github.com/zmkfirmware/zmk/issues/947) for an example of how to implement it right now in your config repo. Closing issue as solved for now, will comment on it when the update happens and the globe key can be implemented normally like any other keycode

**Comment by ReFil** [comment]
This update has happened now so you should be able to use the globe key
