### ISSUE TITLE
No input with latest ZMK update 

### ISSUE THREAD

**Issue by DDRBoxman** [KinesisCorporation/Adv360-Pro-ZMK#249]
I was trying to build a firmware with the update from yesterday but on macOS I wasn't getting any input till I reverted the change.
https://github.com/DDRBoxman/Adv360-Pro-ZMK/commits/V3.0

**Comment by ReFil** [comment]
Was this over USB, BLE or both? With a minor update like that you might need to unpair and repair to the host

**Comment by DDRBoxman** [comment]
I ran into this with both USB and BLE, I also went through and cleared out the connection in the Bluetooth and flashed the setting reset firmware between updates.

**Comment by ReFil** [comment]
I can't replicate this issue on my test computers, windows or an M1 MacBook Pro running MacOS Sonoma. Have you tried connecting it to a phone or other computer?

**Comment by mychmcg** [comment]
The only input I can get is from using the Adv360 Pro factory default firmware (v3.0 10-23-23). Otherwise both my custom keymap(created for the first time last night) and a pure clone of this repo give this error after flashing, on windows 11.
![image](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/18022092/4cfec588-710b-45ed-889b-1355ddb7c4d3)

 Bluetooth works fine with factory defaults as well. With the bad firmware I can tell my layers activate properly and can even clear bluetooth. But my pc cannot hear any of it

**Comment by tslmy** [comment]
+1.

## What I saw

No input from the alphabetical keys. Specifically, I tried these things on my `fn` layer:
- up and down keys (which I mapped to volume in- & decreases) mapped works as expected.
- The letter `m` key (which I mapped to mute) does not work.


## What I tried

I tried restoring with [Adv360 Pro Settings Reset 2.0](https://kinesis-ergo.com/download/adv360-pro-settings-reset-version-2-0/) first, then [Adv360 Pro Settings Reset 3.0](https://kinesis-ergo.com/download/adv360-pro-settings-reset-version-3-0/), and then [Adv360 Pro Factory Default V3.0 (10-23-23)](https://kinesis-ergo.com/download/adv360-pro-factory-default-v3-0-10-23-23/). No input.

I tried restoring with [Adv360 Pro Settings Reset 2.0](https://kinesis-ergo.com/download/adv360-pro-settings-reset-version-2-0/) first, then [Adv360 Pro Settings Reset 3.0](https://kinesis-ergo.com/download/adv360-pro-settings-reset-version-3-0/), and then [Adv360 Pro Factory Default V3.0 (7-6-23)](https://kinesis-ergo.com/download/advantage360-professional-factory-default-7-6-23/). Input works as expected.

I tried restoring with [Adv360 Pro Settings Reset 2.0](https://kinesis-ergo.com/download/adv360-pro-settings-reset-version-2-0/) first, then [Adv360 Pro Settings Reset 3.0](https://kinesis-ergo.com/download/adv360-pro-settings-reset-version-3-0/), and then [my own fork](https://github.com/tslmy/Adv360-Pro-ZMK) which contains this change. No input.

**Comment by ReFil** [comment]
Hi all, many thanks for the reports. A commit that may be causing the issue has been identified and rolled back. Please try rebuilding your personal repos now and reflashing the boards. A settings-reset shouldn't be required but you will need to unpair, BT_CLR and repair to the computer. The build action is rerunning and should have fresh firmware soon: https://github.com/KinesisCorporation/Adv360-Pro-ZMK/actions/runs/6592616006

**Comment by mychmcg** [comment]
Thank you for the fix!

**Comment by ReFil** [comment]
Has that solved your issue?

**Comment by mychmcg** [comment]
Yes, my custom keymap is inputting to my PC correctly

**Comment by DDRBoxman** [comment]
Cool, seems like that fixed it, thanks!
