### ISSUE TITLE
Reset firmware update

### ISSUE THREAD

**Issue by hyojii00** [KinesisCorporation/Adv360-Pro-ZMK#257]
Contrary to the guide document, since updating from the right side first, the LED on the right device is flashing red quickly and does not work.
That's why I don't know how to start bootloder mode. the right side is not working.
I can't connect to my macbook through finder to clear the update file because it doesn't connect separately. 
Does anyone know a solution?

sorry, I'm not good at english

**Comment by ReFil** [comment]
https://github.com/KinesisCorporation/Adv360-Pro-ZMK#overview There are backup hardware reset buttons you can press with a paperclip documented in the user manual

**Comment by KinesisCorporation** [comment]
<img width="239" alt="image" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/37431414/c3e08f27-9adb-4071-8333-9a8cadbce342">

**Comment by hyojii00** [comment]
@ReFil When I press both reset buttons, all the LEDs blink once and then flash red quickly again.
My guess is that the right device is not finding the left device.
Is there any way to revert it via the reset button?

**Comment by KinesisCorporation** [comment]
You only need to press one reset button, but that key module has to be connected to the PC over USB. Reset and Update the left module, then Reset and update the right module.

**Comment by ReFil** [comment]
Please note the reset button must be pressed twice in rapid succession to enter the usb bootloader

**Comment by hyojii00** [comment]
the right module I can reset. but the left side, after click reset button, leds is not blink and turn green. there are just white.

**Comment by KinesisCorporation** [comment]
What number does your serial number start with 1, 2, 3 etc?

Please try using a different USB cable to connect the left module to PC. If it doesn't work the first time then rotate the cable it 180 degrees and try again. Its possible the USB connect is bad. If it still doesn't work please submit a trouble ticket directly to Kinesis and include a video and your serial number. Sorry!

**Comment by hyojii00** [comment]
Thank you. I finally got the pair between the two devices connected and the red LED is no longer blinking.
However, I can't get a bluetooth connection with my MacBook, can I ask for help again?
I see ADV in the bluetooth list, but I can't get it to connect.
I'll try again after work.

**Comment by KinesisCorporation** [comment]
Press the Mod + Windows key to erase any possible pairing in the active Profile on the keyboard. That should ensure the the Profile LED on the left side is flashing "Fast" and the keyboard is ready to pair that Profile. Then you just need to find the "Adv360 Pro" device in your Macbook BT menu and select Connect. If you previously paired the keyboard with your Macbook we recommended "Forget this Device" and then pair from scratch.

Please submit a trouble ticket directly to Kinesis if you need additional assistance. 

https://kinesis-ergo.com/support/contact-a-technician/
