### ISSUE TITLE
cannot flash uf2

### ISSUE THREAD

**Issue by 42x00** [KinesisCorporation/Adv360-Pro-ZMK#261]
Hi,

Everytime I copy uf2 file to the keyboard, the following error occurs:

```
The Finder can’t complete the operation because some data in “left.uf2” can’t be read or written.
(Error code -36)
```

I have tried:

- different mac os
- chmod 777 uf2 file
- different way to enter bootloader
- different uf2 files: Settings Reset, Factory Default Firmware

**Comment by ReFil** [comment]
Hi, just to clarify is the board not updating at all? Error messages with finder do not necessarily mean the operation failed

**Comment by IamGianluca** [comment]
I can confirm that often error messages in Finder (Mac OS) and Files (Linux) do not mean that the firmware update operation failed. After copying the .uf2 files on both the left and right sides, I saw this error, but the operation was successful.

![image](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/4025968/73376df6-5d49-464d-8c40-08d7dd57e8fa)
