### ISSUE TITLE
No ZMK upstream support?

### ISSUE THREAD

**Issue by rah2501** [KinesisCorporation/Adv360-Pro-ZMK#270]
Hi, I was looking at the [list of supported hardware](https://zmk.dev/docs/hardware) for ZMK and the Advantage 360 doesn't seem to be on it.  Have you upstreamed your code?

**Comment by ReFil** [comment]
There's an open PR to upstream the board definition but no plans to upstream the LED indicators code yet

https://github.com/zmkfirmware/zmk/pull/1454

**Comment by ReFil** [comment]
The board definition has now been upstreamed, closing as solved
