### ISSUE TITLE
Mod layer causing build failure?

### ISSUE THREAD

**Issue by simplemachine92** [KinesisCorporation/Adv360-Pro-ZMK#271]
Not sure what the particular reason is but I just deleted the mod layer and the build passes fine immediately after... but heres a trace

![Screenshot 2023-11-17 at 8 02 52 PM](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/21132103/95f13253-4e9f-44a3-b31a-522883f37aa8)

**Comment by ReFil** [comment]
Thanks for bringing this to our attention, it looks like the keymap editor and the new versioning system are conflicting, I will rectify this asap. As a mitigation you can remove the ver macro from the mod layer and builds will succeed again

**Comment by ReFil** [comment]
Rectified now: https://github.com/KinesisCorporation/Adv360-Pro-ZMK/commit/d0ffaf89f8f2cd985b7750bcfeee1feaa5d7435c
