### ISSUE TITLE
MacOS Sonoma (and other v) error message

### ISSUE THREAD

**Issue by Omniscently** [KinesisCorporation/Adv360-Pro-ZMK#294]
The installation of any settings_reset file, or firmware version results in MacOS generating (error code -36). 
"The Finder can't complete the operation because some data in 'filename' can't be read or written"

This is a false negative as the file will still install correctly, it seems.  

How does one avoid this error message? What is causing it? Can it be corrected by editing the repo?

**Comment by ReFil** [comment]
This is a known issue, unfortunately there's no way to address it on our end, it's an apple problem

**Comment by Omniscently** [comment]
I figured, thanks for clarifying. 

I just wanted to post the issue for visibility.
