### ISSUE TITLE
Running `make` on Mac shows `bin/get_version.sh: line 12: <&kp ${char^^}>, : bad substitution`

### ISSUE THREAD

**Issue by jjowdy** [KinesisCorporation/Adv360-Pro-ZMK#304]
This causes `config.version.dtsi` not to be updated correctly.

This is because most Mac default /bin/bash versions are something like 3.2.57 or older (which doesn't know about the ^^ substitution), and Apple has decided to make `zsh` the default shell, so it seems like bash updates aren't too likely in the future.

There's a proposed cross-platform fix in https://github.com/KinesisCorporation/Adv360-Pro-ZMK/pull/303 that uses `tr` in preference to `${char^^}`, but retains the `${char^^}` style as a fallback.

**Comment by ReFil** [comment]
Hi, Thank you for this report, apologies for the delay in addressing this. It's a bit frustrating that apple have done this, but i'm happy to merge your fix. There was another contribution recently that helped when using homebrew bash on macs as well #287
