### ISSUE TITLE
Repeating Key with BT and USB V3.0

### ISSUE THREAD

**Issue by rpisarew** [KinesisCorporation/Adv360-Pro-ZMK#321]
Firmware Version: V3.0
OS: MacOs Sonoma 14.2.1

I had some issues with repeating keys in the older versions, but since V3.0 only the 'D' key is repeating even with a USB cable connected.

**Comment by ReFil** [comment]
Does the problem go away if you downgrade the firmware?

**Comment by rpisarew** [comment]
No it get's even worse with the older versions.

**Comment by ReFil** [comment]
This doesn't sound like a software issue, please try the latest beta firmware which can be found here: https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/259#issuecomment-1880166816

If this doesnt solve the issue you might need to open a ticket: https://github.com/KinesisCorporation/Adv360-Pro-ZMK?tab=readme-ov-file#other-support

**Comment by rpisarew** [comment]
I tested it with the firmware you mentioned and it's still happening. I will then open an support ticket.
