### ISSUE TITLE
Numlock and Capslock led Indicators stopped working

### ISSUE THREAD

**Issue by Zelinzky** [KinesisCorporation/Adv360-Pro-ZMK#330]
Numlock and Capslock led Indicators stopped working with commit [4a5003a](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/commit/4a5003a0d4e6c1cf26512d79d4358455bccb00a8).

**Comment by ReFil** [comment]
As per the suggestion in the PR you need to unpair and repair to the host

**Comment by Zelinzky** [comment]
@ReFil Sorry for the noise somehow didn't see that last line on the PR.
Thank you for the quick response.
