### ISSUE TITLE
Intermittent malfunctions

### ISSUE THREAD

**Issue by ebzzry** [KinesisCorporation/Adv360-Pro-ZMK#349]
After upgrading to the new firmware, I noticed that the keyboard stops sending keystrokes seemingly randomly. 

I’m using the Kinesis Advantage360 Pro on macOS Sonoma 14.2.1.

**Comment by ReFil** [comment]
Try changing `CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y` to `CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n` in adv360_left_defconfig and adv360_right_defconfig

**Comment by ebzzry** [comment]
I did that and I haven’t seen those malfunctions, so far. I’ll continue testing for the next hours, then I’ll come to this issue.

**Comment by ebzzry** [comment]
I can confirm that I don’t see the erratic behavior, anymore. I’m closing the issue.
