### ISSUE TITLE
Update Readme on how to install Adv360-Pro-ZMK on Ubuntu

### ISSUE THREAD

**Issue by momiforgotthesemicolon** [KinesisCorporation/Adv360-Pro-ZMK#372]
It took me a while to realize that instead of the `docker build` / `docker pull` I have to invoke `make` in the terminal after cloning the repository. Can you please update the steps on how to install this on Ubuntu?

**Comment by ReFil** [comment]
This is documented already here: https://github.com/KinesisCorporation/Adv360-Pro-ZMK?tab=readme-ov-file#build-firmware-locally
