### ISSUE TITLE
NOT ENABLE INT keys at Mac OS Sonoma

### ISSUE THREAD

**Issue by yuuna** [KinesisCorporation/Adv360-Pro-ZMK#410]
Helllo

I set adv360_left_defconfig
`CONFIG_ZMK_HID_KEYBOARD_EXTENDED_REPORT=y `

but I can't enable INT keys(INT1..5)

so I check BT logs at my Mac, I found that only after I enable this config , it causes L2CAP errors.

<img width="1201" alt="スクリーンショット 2024-03-16 9 53 09" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/381582/57538450-66a2-4fc9-9541-d9a928159d6a">

OS: Mac Sonoma 14.3.1
Hardware: Mac Studio 2022(M1 Ultra)

**Comment by ReFil** [comment]
After changing that setting you need to unpair and re pair the keyboard to the computer

**Comment by yuuna** [comment]
@ReFil 

I unpair the keyboard ( Mod + Winkey) and delete profile from Mac and reboot it.
But it still show same error.

**Comment by ReFil** [comment]
Is N key rollover enabled?

**Comment by yuuna** [comment]
@ReFil 
adv360_left_defconfig
```
CONFIG_ZMK_HID_REPORT_TYPE_NKRO =y
CONFIG_ZMK_HID_KEYBOARD_EXTENDED_REPORT=y
```

After I set NKRO=n , build if failed.
<img width="989" alt="スクリーンショット 2024-03-16 21 32 57" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/381582/c7ad13ee-226b-4897-86b6-f66919b089f3">

**Comment by yuuna** [comment]
I think parameter will changed CONFIG_ZMK_HID_KEYBOARD_EXTENDED_REPORT to CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT.

I will change this parameter.

https://zmk.dev/docs/config/system

**Comment by ReFil** [comment]
Hi, Did changing that updated parameter work for you?

**Comment by ReFil** [comment]
hello, just following up on this, is it working?

**Comment by ReFil** [comment]
Hello, just following up again, if i dont hear from you in the next 24 hours i will close this issue as solved, thank you
