### ISSUE TITLE
Adv360-Pro-GUI web cannot be opened

### ISSUE THREAD

**Issue by lbtrace** [KinesisCorporation/Adv360-Pro-ZMK#414]
hi, kinesis I meet  a issue:
- Issue
Does the adv360 pro keyboard (already connected to PC via Bluetooth) need to be set up when opening the web? [Adv360-Pro-GUI web](https://kinesiscorporation.github.io/Adv360-Pro-GUI) cannot be opened, always display: "waiting for api"
- OS
macos sonoma 14.4
- Hardware
Mac Book pro M1

**Comment by ReFil** [comment]
Hi, you do not need the board to be connected to use the GUI. Please ensure you are not using a web extension such as ghostery when using the GUI as it will block the connection to the backend API, alternatively "trust" the GUI website so it does not block the API connections

**Comment by lbtrace** [comment]
thx, I will try it
