### ISSUE TITLE
Possible typo in `adv360_left_defconfig`?

### ISSUE THREAD

**Issue by khoek** [KinesisCorporation/Adv360-Pro-ZMK#427]
I can't seem to find the config var `CONFIG_ZMK_HID_KEYBOARD_EXTENDED_REPORT` referenced in `adv360_left_defconfig` in the main ZMK repo, but I can find the very similar `CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT` (noticed while discovering https://github.com/zmkfirmware/zmk/issues/2253 actually). Is this a typo/old name from when the option was being developed?

Confusingly, this other name seemed to me to work just as well as the documented one, but I might have been too hasty in my testing. Perhaps this is all fine and there is some sort of compatibility/alias that I've missed which explains this?

**Comment by khoek** [comment]
Ah! I see it's in the custom fork. No worries. Sorry for the noise.

**Comment by ReFil** [comment]
This feature was developed and implemented in the custom repo first, then upstreamed later. During the upstreaming process the zmk maintainers wanted the name of the kconfig option changed to better describe the option. As a result we now have an additional kconfig option  in the custom fork to assign it properly for users
