### ISSUE TITLE
Is it possible to customize layer colors?

### ISSUE THREAD

**Issue by sharwell** [KinesisCorporation/Adv360-Pro-ZMK#45]
By default, the 'kp' layer lights up the layer LED as white, 'fn' lights it as blue, and 'mod' lights it as green. Is it possible to customize the color of this LED and/or assign colors to other layers?

**Comment by craftyguy** [comment]
this builds a branch from a forked zmk repo, where the indicator LED stuff is implemented: 

https://github.com/zmkfirmware/zmk/compare/main...ReFil:zmk:adv360-z3

And @ReFil has a doc in that branch explaining how to enable it for a device: https://github.com/zmkfirmware/zmk/compare/main...ReFil:zmk:adv360-z3#diff-b7b69bea1bf24b1c8781e3875719551c6addfdc5654cc8efb70fd76898311b58R19

however I don't see any of that implemented in this repo... so... 🤷🏽

**Comment by ReFil** [comment]
The layer colours were not designed to be changed, although it can be done by forking my adv360_z3 branch, redirecting the user config repo to point to your fork and changing the individual r g and b values in app/src/rgb_underglow.c. The led indicators function mentioned in those docs is not referring to the layer indication, it's a different subsystem. I've implemented user configurable per layer lighting for a different project before (https://github.com/ReFil/zmk/commit/2f7c0420b386637b630693398d28aa4beed6c898)  but don't have the time to port it to the adv360 branch. If anyone else is willing to do so I'd be more than happy to pr it in, it shouldn't be too hard and won't cause issues

**Comment by ReFil** [comment]
Closing as changing this is not in the roadmap
