### ISSUE TITLE
Receive error code -36 after when trying to flash the firmware

### ISSUE THREAD

**Issue by ujwal-jain** [KinesisCorporation/Adv360-Pro-ZMK#453]
Hello, I follow instructions to flash the firmware after modifying   my layout with the GUI for the Advantage Kinesis 360 pro. When i try to copy the [uuid]-left.uf2 to my left keyboard or right keyboard in bootloader mode, the program crashes and i get the error -36. 
<img width="433" alt="Screenshot 2024-04-20 at 2 41 53 PM" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/20618651/5639b03f-fc74-4e08-bc19-da41abf9a572">

I'm struggling to figure out if it's something I've missed or if it's a faulty device. Appreciate any help, thanks!

**Comment by ReFil** [comment]
Have you used the mod+v key combination to check the version flashed to the board? Finder is known to throw error codes but the board still flashes

**Comment by ReFil** [comment]
Hello, just following up on this, has the firmware been properly updated?

**Comment by ReFil** [comment]
Closing issue as solved, the -36 issue is known to be spurious and does not stop the board flashign
