### ISSUE TITLE
Mod + Hotkey 3 does not work

### ISSUE THREAD

**Issue by InhyukYee** [KinesisCorporation/Adv360-Pro-ZMK#482]
i just flashed left keyboard firmware by using mod + Hotkey 1

but when I'm trying to access to right keyboard by using mod + Hotkey 3, it does not load recognize it as usb drive. 

What should i do?

**Comment by InhyukYee** [comment]
self answer

It seems like mine firmware is so old that Mod + Hotkey 3 didn't work

There is another way to enter into bootloader mode. 

press Reset button twice. 

For more detail, read Users Manual p14 '5.9 Bootloader Mode'

**Comment by KinesisCorporation** [comment]
Yes, we prefer using the Reset-button method because it doesn't require both modules to be connected.
