### ISSUE TITLE
No Space Left on drive error on When updating firmware for Advantage Pro 360

### ISSUE THREAD

**Issue by numenbit** [KinesisCorporation/Adv360-Pro-ZMK#487]
I was able to change my keybindings for the keyboard a few times did the firmware upgrade did left and right no problem.   I was getting some errors but I just ignored and everything updated with the new keybindings no problem.   

Now a few months later and I want to change my keybindings again and now I am trying to drag the file to the keyboard mounted drive on my Mac and I am getting not enough space on drive error.    

Because of this error I can not update my changes.   I tried deleting the files on the mounted volume and they always come back so not sure how to get more space.   Maybe my other updates filled up the keyboard drive? 

How can I make space I tried deleted one of the files that was around 1.4MB but that one kept coming back CURRENT.UF2 something like that cant remember.    Going to try to use the console but since keyboard is not enabled I guess I will have to attach another keyboard.   

Any ideas?

![kinesis_cropped](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/96230937/b7b27115-cbe3-40aa-a88c-064afddd2894)

**Comment by ReFil** [comment]
The drive is a virtual drive, so you shouldn't have a problem with free space. Deleting the files that are there wont change that. The drive should say it's 32MB approx, is that the case?

**Comment by ReFil** [comment]
Following up on this, are you still having this issue?
