### ISSUE TITLE
Macro issues when updating keymap

### ISSUE THREAD

**Issue by gituser768** [KinesisCorporation/Adv360-Pro-ZMK#492]
I am trying to transition to v3 of the firmware. I created a new branch off the V3 tag and updated the keymap using the web configurator. It looks like when doing this, it duplicated some macros which caused some compilation failure. I removed the duplicates, but now i have another issue which seems to also be related to macros. Could some take a look?

https://github.com/dmh43/Adv360-Pro-ZMK/tree/dh-new

**Comment by ReFil** [comment]
https://github.com/dmh43/Adv360-Pro-ZMK/blob/1e92447bb0d44600f064d0db18974a7245d52cb2/config/adv360.keymap#L45 here you have `&mo` without a layer to go to, change it e.g. to `&mo 3`

**Comment by ReFil** [comment]
I can see your builds are succeeding now so I'm going to close this issue out as solved

**Comment by gituser768** [comment]
thank you!
