### ISSUE TITLE
Macro not firing

### ISSUE THREAD

**Issue by Odaym** [KinesisCorporation/Adv360-Pro-ZMK#494]
Hi, great work on the keyboard, I really love it.

I'm on a late 2023 Mac running Sonoma. I have some shortcuts for switching to different workspaces:
<img width="466" alt="Screenshot 2024-06-06 at 08 44 00" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/2f20ece3-f810-4b5c-a76c-a2faafae0c12">

I wanted to make these as macros so that I could have the Hotkeys (1 and 2 for example) run them in 1 button.

What I did was this:

- Add them to the list of Macros under Edit macros the in the GUI mapper
<img width="606" alt="Screenshot 2024-06-06 at 08 45 05" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/de5defa2-f69d-4729-a2ba-91eea43d19a0">

- Assign them to the desired keys in the GUI mapper
<img width="418" alt="Screenshot 2024-06-06 at 08 47 50" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/603e77a6-30ad-4500-8b7e-db688b17578f">

- Flash the new firmware successfully onto the keyboard

However, running them yields wrong/no results:

- Running the first hotkey (1), just produces an F1 action which displays mission control
- 2 does nothing

I tried to add an FN into the macro to see if it would help but it didn't, same result. The reason being is that on the Adv360 I do have to press FN to get to the actual F1/2/3 keys, but on my mac keyboard or the Typematrix, I just do Shift + F1.
<img width="700" alt="Screenshot 2024-06-06 at 08 51 37" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/f23e87d5-9b33-4635-9c0d-3df7a9b52005">

This is my current config: https://github.com/Odaym/Adv360-Pro-ZMK/tree/V3.0

Any help would be appreciated, thanks a lot!

**Comment by ReFil** [comment]
That macro will currently tap the shift then tap the f1 key, you may need to write your own macro or use a different editor such as https://nickcoutsos.github.io/keymap-editor/ to create a macro that presses shift, then taps f1 then releases shift

**Comment by Odaym** [comment]
Thanks for the response, so Macros basically are keys in succession, there can be no holding down this key and pressing down that key meanwhile.

I opened an issue in the Keymap-editor repo but if you have any experience with it? would it look something like this? Basically a Macro in itself as well but it has Press/Tap options

![image](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/437a089f-2b52-4ca8-9aaa-5d7f8a3c8143)


Thanks!

**Comment by ReFil** [comment]
Macros can have press, tap and release options. You'll want to use &macro_press LSHFT, &macro_tap F1, &macro_release LSHFT

**Comment by Odaym** [comment]
ok clear, well I'll try this today and will write back what and how it works, but let me just keep this open till then, thanks

**Comment by Odaym** [comment]
yup that worked and it's much simpler than i thought, here's all you need to do to achieve that

<img width="874" alt="Screenshot 2024-06-06 at 19 22 20" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/753054/3df7c4d9-59fb-47a3-9e87-3af6bcd92853">

thanks a lot for all your help!
