### ISSUE TITLE
Example for disabling nkey rollover?

### ISSUE THREAD

**Issue by cweidenkeller** [KinesisCorporation/Adv360-Pro-ZMK#502]
Do y'all happen to have an example to disable nkey rollover? 

Thanks!

**Comment by ReFil** [comment]
https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/0c975742d105747d551b41dc4056e5ae1c74982d/config/boards/arm/adv360/adv360_left_defconfig#L64

Change =y to =n

**Comment by cweidenkeller** [comment]
Dope thanks
