### ISSUE TITLE
How do I disable a key

### ISSUE THREAD

**Issue by tyleradams** [KinesisCorporation/Adv360-Pro-ZMK#517]
I want to disable a key. I have an odd setup where it's often pressed but I want it to no-op so it doesn't do anything, how can I do this?

**Comment by tyleradams** [comment]
I have a 360 USB running stock firmware

**Comment by ReFil** [comment]
Are you using the pro or the smartset version? This repository is only for the pro

**Comment by tyleradams** [comment]
well now that PRO has clicky white, if it supports this too i might buy a PRO

**Comment by KinesisCorporation** [comment]
You can use the [null] token in the App or via Direct Programming on the USB SmartSet version to disable any key.
