### ISSUE TITLE
Community PRs

### ISSUE THREAD

**Issue by TravisHi** [KinesisCorporation/Adv360-Pro-ZMK#52]
Hey guys, will you accept PRs from users? I feel like there's some quality of life things I could add to the repo (e.g. commented keyboard layouts in the .keymap file etc.). It might help people relatively new to keyboard configuration to add their own keymaps if they can see what's going on easier.

**Comment by craftyguy** [comment]
I don't speak for the owners of this repo, but they've (so far) been receptive of patches from folks in the community: 

https://github.com/KinesisCorporation/Adv360-Pro-ZMK/pulls?q=is%3Apr+

I hope it keeps going :)

**Comment by KinesisCorporation** [comment]
In general yes. We rely on @ReFil to evaluate PRs from users.
