### ISSUE TITLE
how to assign two key type (macro?)

### ISSUE THREAD

**Issue by mudduck** [KinesisCorporation/Adv360-Pro-ZMK#521]
sorry if this is wrong spot for this but looking for how to assign something like 'ctrl+c, x, v' etc to one key and i cannot find it in the menu in smartset when i click on key i want to remap/assign.

example: 

in fn1 layer i want c, v, x keys to be mapped to cntrl+c, v, respectively. (im asking cuz i cant find (and find it odd you can control multimedia etc but not something as simple as copy/paste? 

again, i may be missing something obvious, if so pls point that out. 

thx!

**Comment by KinesisCorporation** [comment]
Those types of commands don't actually require a macro in ZMK. Try this:

&kp LC(C)
&kp LC(X)
&kp LC(C)
