### ISSUE TITLE
f13 to f24 issue

### ISSUE THREAD

**Issue by arabshapt** [KinesisCorporation/Adv360-Pro-ZMK#525]
Hi!
Is it CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT or CONFIG_ZMK_HID_KEYBOARD_EXTENDED_REPORT?
The one on kinesis website and in this documentation didn't work for me, but CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT did. 🙂

**Comment by ReFil** [comment]
The upstream ZMK one has superceded the internal one, the internal one should enable the upstream one, thank you for bringing it to my attention

**Comment by ReFil** [comment]
I've done some more testing and confirmed that the kinesis one enables the upstream one, not sure why it wasn't working properly for you, I'm going to close this issue as solved for now
