### ISSUE TITLE
Freestyle2 Blue some keys tying gibberish 

### ISSUE THREAD

**Issue by jrmacek** [KinesisCorporation/Adv360-Pro-ZMK#533]
for example, the 's' key when pressed types s$, the 't' key types t . I can't figure out from the usual manual how to reset the keyboard. there is no "smartkey" as far as I can tell.

**Comment by KinesisCorporation** [comment]
Hi JR,

This is a forum specifically for the Advantage360 Pro. There is no way to reset the Freestyle2 Blue. It's possible your keyboard is reaching the end of its natural life. If you would like to submit a trouble ticket we can see if we can get it working for you and advise on your warranty status (Factory warranty is 2 years from the date of purchase).

https://kinesis-ergo.com/support/contact-a-technician/
