### ISSUE TITLE
mac command+C

### ISSUE THREAD

**Issue by rafahoro** [KinesisCorporation/Adv360-Pro-ZMK#535]
Is it possible to program a macro or simple key binding to copy/paste using https://kinesiscorporation.github.io/Adv360-Pro-GUI/?

I would like to use the '1'...'4' keys, to copy/paste/cut/undo. but I can't find how to press/hold a the 'command' in the macros. 
Nor how to bind 'command+C' to a single key.

If not possible to do that in https://kinesiscorporation.github.io/Adv360-Pro-GUI/, what are the key codes for press-and-hold the 'command' key for macros. Or to press at the same time 'command'+C in key bindings?

**Comment by KinesisCorporation** [comment]
Yes! And you don't even need to use a macro for that. Use the short codes for the modifiers (LS/RS, LC/RC, LG/RG, LA/RA) and then input the second key action in the Keymap Editor

<img width="90" alt="image" src="https://github.com/user-attachments/assets/7e41a6ca-f3d5-4f01-a521-10620f8fcf2b">
