### ISSUE TITLE
Windows 10 Bluetooth randomly disconnects and reconnects

### ISSUE THREAD

**Issue by jmarais** [KinesisCorporation/Adv360-Pro-ZMK#536]
# Problem
The Bluetooth will randomly disconnect and reconnect after about 5-10 seconds.
# Attempted Solutions
I looked through all the past issues regarding Bluetooth for info. 
I tried the `settings-reset-v3.0` on the left/right halves and then formatting the latest V3 (with my key profile) and `CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n` in the left/right config files.
# Other info
For reference here is my diff against the V3 branch:
[diff against V3](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/compare/V3.0...jmarais:Adv360-Pro-ZMK:V3.0.1)

I am connecting to my motherboard's Bluetooth with this network adapter (about 1meter away):
[Intel Dual Band Wireless-AC 3168 ](https://www.intel.com/content/www/us/en/products/sku/94854/intel-dual-band-wirelessac-3168/specifications.html)
With firmware version: `HCI 8.4352 / LMP 8.4352`

The DC happens quite frequently to the point that I am creating this issue asking for anything suggestions I might have missed.

**Comment by ReFil** [comment]
Intel Wireless can be problematic, although the experimental features flag should make things work

**Comment by jmarais** [comment]
I will switch it back OFF again and see what happens.

**Comment by jmarais** [comment]
So steps I took.
1. Switch off both sides. 
2. Remove the adv360 device from my windows bluetooth devices.
3. flash left then right with the `settings-reset` firmware.
4. downloaded my firmware with [CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n](https://github.com/jmarais/Adv360-Pro-ZMK/actions/runs/10301243527)
5. flashed left and then right with the new firmware (about 30minutes ago).
6. pair the device as a new device in windows.

It just did a disconnect/reconnect loop.

**Comment by jmarais** [comment]
If there is no other config options or values to try, is it possible to recommend a USB Bluetooth receiver model/brand/vendor that is known to work with the Bluetooth module in the keyboard?

**Comment by ReFil** [comment]
We've had good success with the TP link UB4A

**Comment by jmarais** [comment]
Thanks. I will try that receiver.

**Comment by jmarais** [comment]
Been using the tp-link UB5A for about 5 days now. No issues to report. Thanks.

**Comment by KinesisCorporation** [comment]
Great. Please keep us posted.
