### ISSUE TITLE
How to reprogram Windows/home button to AltGr using Graphical Keymap Editor (Newbie here ;))

### ISSUE THREAD

**Issue by VetMags** [KinesisCorporation/Adv360-Pro-ZMK#55]
Hi!

Just bought my new Kinesis Advatage 360 Pro and never used ZMK before so on a steep learning curve her ;)
As I live in Sweden I've ordered Nordic keycaps and need to reprogram the layout on several keys but I'm having several problems/questions. 

1. I want to change the "windows home" button to become AltGr instead. How do I do this using the keymap editor as I can't seem to find a specific option/key for AltGr.

2. Once I've actuallt got an AltGr there are several more keys like the number 8 key in Nordic countries that has 2 additional "special characters" on the same key that utilises AltGr. 
 For example when I press the number 8 key+ Shift I would like to get at "left parenthesis"  (
and when I press Key 8+AltGr I would like to get a "left bracket" [

3. How do I find and assig special letters such as Å ( an A with a ring above (ALT+0197). I can't find them in the list so assume I have to aadthemm in som eother way? Can I still use the Graphical Keymap Editor?

When I look at the "orgiginal input" on the Keymap Editor and "hover" over a certain key I can se that some keys have 2 different possible characters but when I want to change them I only seem to be able to put in a single characters but not the special characters as well. 

How do I do this?

I newbie question I know but was hoping for a "resonably easy" way to be able to remap my 360 for Nordic languages using the Keymap Editor rather than have to learn how to code it manually. 

Hope you can help!! :)

Think I need a "Advantage 360 Graphical Keymap Editor for dummies" youtube video :)))

**Comment by ReFil** [comment]
AltGr is RALT as far as i know, the specificities of the nordic layout should be handled in the software layer when you select the keyboard layout in your OS

**Comment by ReFil** [comment]
Hi, did you managed to figure it out? do you need further help? to keep the repo clean if you dont reply in 48H i'll close the issue
