### ISSUE TITLE
LEDs burning my eyes.

### ISSUE THREAD

**Issue by adofse** [KinesisCorporation/Adv360-Pro-ZMK#560]
As mentioned https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/129,  LEDs brightness intensity is too strong (100%?) in any lighting conditions which results in burning my eyes.

|OFF| ON|
|-|-|
|<img width="608" alt="image" src="https://github.com/user-attachments/assets/4ae1a9a4-dddb-49c7-812f-140ff5bc45fa">|<img width="608" alt="image" src="https://github.com/user-attachments/assets/cb2252a8-6ee0-43ff-a820-215a0022882b">|
||See a video in https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/129 |

## To reproduce
I observed the following two patterns that LEDs shine 100%.
- a. Turn on power
- b. Double click the Bootloader Button (to flash firmware)

## Expected Behaviour
User can change LED brightness intensity.

## Ref
@KinesisCorporation suggested a guide in https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/129#issuecomment-1494585400, but the instruction `Edit line: CONFIG_ZMK_BACKLIGHT_BRT_SCALE=25` is for BACKLIGHTs not LEDs so It won't help.

**Comment by ReFil** [comment]
The short bright flash when the board powers up andd is in bootloader is unavoidable I'm afraid, it is an artifact of the bootloader and cannot be configured

**Comment by adofse** [comment]
@ReFil Does that mean you can't change that behavior in https://github.com/ReFil/zmk/tree/adv360-z3.5 or any other dependencies ?

> [!warning]
> Seeing too bright lights could cause serious health harms for human eyes so it should be cared under Kinesis Corporation's responsibility.

**Comment by adofse** [comment]
Now we know how @KinesisCorporation treats their users since it's been 3 days when I report potential health harms issue.

I believe it's too early to take advantage open source ZMK for @KinesisCorporation  as they claim they are small private company. 

Highly Disappointed!

**Comment by KinesisCorporation** [comment]
Unfortunately this is not user-configurable. 

Please contact Tech Support and link them to this discussion. We will accept a return of the keyboard.

https://kinesis-ergo.com/support/contact-a-technician/

**Comment by adofse** [comment]
@KinesisCorporation 

> Unfortunately this is not user-configurable.

Please elaborate this. Editing source code in https://github.com/ReFil/zmk/tree/adv360-z3.5 could solve this problem?
If not, are you willing to contact someone who develop bootloader firmware?

**Comment by KinesisCorporation** [comment]
Hi,

The next time we do work on the bootloader we will explore whether the LEDs can be dimmed. If you decide to keep the keyboard we suggest not looking directly at the LEDs while opening the bootloader. We are still happy to process a return/exchange of the keyboard.

**Comment by adofse** [comment]
> The next time we do work on the bootloader we will explore whether the LEDs can be dimmed.

@KinesisCorporation Could you assign @ReFil to take a look?

**Comment by adofse** [comment]
@KinesisCorporation Make a statement about this issue. Don't run away from this issue.
