### ISSUE TITLE
Left Module is suddenly unresponsive

### ISSUE THREAD

**Issue by amrelnag** [KinesisCorporation/Adv360-Pro-ZMK#594]
Left Module stopped working, even while connected through USB. 
When I turn bluetooth on, the Fn LED quickly blink green once and then the left module is unresponsive.

I tried the bootloader, but it is also unresponsive, doesn't blink white like the right module. 

Battery should be well charged as I left it charging overnight. 
Has anyone faced this before?

**Comment by KinesisCorporation** [comment]
Hmm. That sounds like a hardware failure of some kind. Please submit a ticket and we'll get it sorted for you. Sorry!

https://kinesis-ergo.com/support/contact-a-technician/

**Comment by amrelnag** [comment]
Already cut a ticket #E-27362, thanks for the response.

**Comment by KinesisCorporation** [comment]
great!
