### ISSUE TITLE
Reprogramm Windows Key to ALTGR

### ISSUE THREAD

**Issue by blex2** [KinesisCorporation/Adv360-Pro-ZMK#613]
I have tryed to map the windows key to alt+gr
On the old advanced pro there was swtich between "pc(altgr) and Windows" Mode. 

I would like to get the ALTGR working. I tryed RIGHTCTL(RIGHTALT) in the config this seems not realy to work. In Windows the "@" on the german Q ist working. The "€" on the "e" not. In link neather is working.

What is the korrekt way for my zmk layout on the key?

**Comment by KinesisCorporation** [comment]
"Alt Gr" is just Right Alt.

**Comment by blex2** [comment]
Thanks a lot. I tried it and it worked perfect.

**Comment by KinesisCorporation** [comment]
You bet!
