### ISSUE TITLE
macro doesn't work 

### ISSUE THREAD

**Issue by shiqicao** [KinesisCorporation/Adv360-Pro-ZMK#69]
I added a macro and assign it to HK 3, but after build and update. Nothing happens if I press HK 3. Is there something I did wrong? Here is my change, https://github.com/KinesisCorporation/Adv360-Pro-ZMK/commit/ff9a7fcf0f3f148cbd767d12a9ad6f0ca6974cc1

Thanks

**Comment by dylan-jh** [comment]
It looks like you may have assigned the macro to the position of HK4 (the lowest key in the inner column of 3). Can you test that?

**Comment by shiqicao** [comment]
doesn't work, I pressed "4", which is on the left side of "H"

**Comment by KinesisCorporation** [comment]
Unfortunately we're not able to troubleshoot individual builds. Best approach is to start totally from scratch with a one-key macro to see if that works. Then make one change at a time to see where things go wrong.

**Comment by shiqicao** [comment]
@KinesisCorporation thanks for replying, would you give me an example of how to configure a macro, for example, you can send me a git branch, where just a macro is added. Then I can try to test it on my side. Thanks!

**Comment by KinesisCorporation** [comment]
There are some example macros in the default firmware. You should try assigning one of those to HK3 and then try editing that macro either through the configuration files or the GUI. Good luck!

We were able to get your password macro working last night so it should be a simple matter once you figure out what you are doing wrong.

**Comment by shiqicao** [comment]
by the way, when a macro is assigned to HK3(the key left to Y), do I press only HK3, or I need to press some modifier key?

**Comment by KinesisCorporation** [comment]
Just hotkey 3

**Comment by shiqicao** [comment]
previously I only updated firmware for right one, this seems the problem. After updated firmware for both, macro works!

**Comment by ReFil** [comment]
Keymap changes need both sides updating. Closing as solved

**Comment by KinesisCorporation** [comment]
Yeah, you need to install the update on both left and right modules per all of the instructions. Glad you got it working.
