### ISSUE TITLE
bluebooth stops working 

### ISSUE THREAD

**Issue by shiqicao** [KinesisCorporation/Adv360-Pro-ZMK#70]
the profile keeps flashing, it disconnected immediately after connected

**Comment by ReFil** [comment]
Sorry this isn't really enough information to diagnose the issue, please try clearing the bluetooth profile using Mod + Windows, then unpair in whatever OS you're using and try again

**Comment by ReFil** [comment]
Hi do you have an update? Will close this issue in 24h otherwise

**Comment by shiqicao** [comment]
The problem is resolved, after I follow the instructionson the manual
