### ISSUE TITLE
Build action failed 

### ISSUE THREAD

**Issue by thinium** [KinesisCorporation/Adv360-Pro-ZMK#8]
Hi! I just tried to build the ZMK firmware for the first time. But the action failed in two places. Is it possible there is an issue in the build script? How can I fix them?

Here is my build action: https://github.com/thinium/Adv360-Pro-ZMK/actions/runs/3061013510/jobs/4940248396#step:8:37

![Screenshot 2022-09-16 at 09 18 20](https://user-images.githubusercontent.com/1383198/190584837-2fb105b3-5aa2-4761-84b2-861d29041cb2.png)
![Screenshot 2022-09-16 at 09 18 30](https://user-images.githubusercontent.com/1383198/190584843-4d4fdf4f-7d39-4e29-b604-ac1881ea0c64.png)

**Comment by thinium** [comment]
fixed.... it's caused by an empty biding

**Comment by KinesisCorporation** [comment]
Great!

**Comment by dustMason** [comment]
i'm having the same error - can you describe how you fixed it? i changed only a single key binding but am seeing this error on my github actions build

**Comment by thinium** [comment]
@dustMason in my case there is a macro that is empty (it contains no keys). After removing that macro everything works fine. Yours seems to be a different issue from mine. @KinesisCorporation it would be great to publish a list of typical mistakes and how to fix them. Also for newbies to build action how to debug it. The ZMK people told me that your version has diverged a lot from theirs (it seems that yours is based on a rather old version), and they might not be able to provide much help in the future.

**Comment by dustMason** [comment]
Thank you – it turns out that my error was also caused by an empty macro. I rolled back my changes one by one until i discovered the empty macro. It's easy to make this mistake in the GUI editor – I suggest adding a validation in the editor to prevent saving an empty macro.

**Comment by KinesisCorporation** [comment]
Appreciate all the dialogue guys!

1. We're about to publish an update that merges our custom features with the latest from ZMK.
2. And we're starting a troubleshooting tip with a list of common mistakes here:
https://kinesis-ergo.com/support/kb360pro/#troubleshooting
