### ISSUE TITLE
Binding Mouse Clicks/Actions as described in Manual

### ISSUE THREAD

**Issue by hh** [KinesisCorporation/Adv360-Pro-ZMK#87]
I'd like to use mouse clicks and actions as described in [Advantage360-Pro-ZMK-KB360-Pro-Users-Manual-v4-7-22.pdf](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwip-sO75az8AhUsZWwGHSH4D18QFnoECA0QAQ&url=https%3A%2F%2Fkinesis-ergo.com%2Fwp-content%2Fuploads%2FAdvantage360-Pro-ZMK-KB360-Pro-Users-Manual-v4-7-22.pdf&usg=AOvVaw27G9eGeWEysvGCgc6QpARw), but I'm unable to find the key(mouse?) codes:

From Page 13 of the manual:
> 5.2 Four new HotKeys

> These four keys can be programmed to perform any single key action, mouse click, macro and more.

From Page 17 of the manual:

> 6.4 ZMK Token List

> ZMK supports a wide array of keyboard actions (letters, numbers, symbols, media, mouse actions). Visit the link below for a handy list of tokens to reference when programming your keyboard.
https://zmk.dev/docs/codes/

**Comment by hh** [comment]
There is a reddit discussion, but would love to hear from Kinesis on this as it's in the manual but possible not supported by the Adv360-Pro-ZMK yet. 

https://www.reddit.com/r/ErgoMechKeyboards/comments/w39hpt/zmk_users_how_to_add_mouse_keys/

**Comment by KinesisCorporation** [comment]
That was our mistake in the manual. It was copied over from the SmartSet model keyboard which supports mouse clicks and movements.

One of our power users has built an experimental branch of ZMK firmware for the 360 that has Mouse Keys supports. It doesn't have the indicator lighting features and its still experimental, but feel free to take a look.

 https://github.com/urob/adv360-demo-config

**Comment by ReFil** [comment]
Closing as resolved, Mouse key support will be added to this repo when it's merged into ZMK main

**Comment by sudoFerraz** [comment]
@ReFil any updates on such support?

**Comment by ReFil** [comment]
Mouse support still hasn't been merged into zmk main unfortunately

**Comment by sudoFerraz** [comment]
@ReFil Any plans to add an official beta branch with mouse support from ZMK?
