### ISSUE TITLE
Why is the Adv360-Pro-GUI Repository not Public?

### ISSUE THREAD

**Issue by steinbrueckri** [KinesisCorporation/Adv360-Pro-ZMK#9]
I ask because it is not possible to select "none" for a key in the Adv360-Pro-GUI. I love to contribute and create a PR but it's not possible. 😢

**Comment by KinesisCorporation** [comment]
Just toggled to public. Appreciate your contributions!

**Comment by steinbrueckri** [comment]
@KinesisCorporation Thanks 🙏

**Comment by steinbrueckri** [comment]
@KinesisCorporation After some research, it makes sense why "Adv360-Pro-GUI" was not public because it is just the build from the Vue App in the Repository https://github.com/KinesisCorporation/Adv360-Pro-KeymapEditor. 

Correct me if I'm wrong but the KeyCodes are loaded from the Vue application from the [adv360-pro-api](https://adv360-pro-api.herokuapp.com/keycodes). So I guess I cannot fix the issue by myself. 😔

**Comment by Giljjj** [comment]
![image](https://user-images.githubusercontent.com/33606456/190860159-b9d360ee-6c40-4114-ab0a-c14e1d4e9561.png)
Looks like &none is a behaviour (like &kp and &trans) and not a keycode.

**Comment by steinbrueckri** [comment]
THX for the clarification I was not aware of that. @Giljjj @KinesisCorporation
