### ISSUE TITLE
Build failure on MacOS using podman

### ISSUE THREAD

**Issue by humblehacker** [KinesisCorporation/Adv360-Pro-ZMK#90]
```
Error: preparing container d3ed7931ce28a2b3f8dccb090151f120c89435662bf43e646923c88f7c167449 for attach: lsetxattr Adv360-Pro-ZMK/config/adv360_left.keymap: operation not supported
```

The changes in PR #58 are the culprit. After reverting locally, I'm able to build successfully.

For reference: https://github.com/containers/podman-compose/issues/509

**Comment by ReFil** [comment]
Thanks for bringing this to my attention, will investigate

**Comment by ReFil** [comment]
Would you be able to test my PR? I dont have a mac to test on

**Comment by kibner** [comment]
> Would you be able to test my PR? I dont have a mac to test on

I have an M2 MBA on Ventura 13.1 and the PR still doesn't work. I ran `make clean` and then `make`. This is my error:

```
STEP 9/9: CMD ["./build.sh"]
COMMIT zmk
--> deed133ce29
Successfully tagged localhost/zmk:latest
deed133ce29b5c4f550a8a7dd2c2279c77b14f51865d30a4f28b72b67b0c5918
/opt/homebrew/bin/podman run --rm -it --name zmk \
                -v /Users/kibner/src/Adv360-Pro-ZMK/firmware:/app/firmware:z \
                -v /Users/kibner/src/Adv360-Pro-ZMK/config:/app/config:ro,z \
                -e TIMESTAMP=20230113202756 \
                zmk
Error: preparing container 24c739ca68cf1ba4724e869dc56491774750e777a4542628153483c298ebfa34 for attach: lsetxattr /Users/kibner/src/Adv360-Pro-ZMK/firmware: operation not supported
make: *** [all] Error 126
```

**Comment by ReFil** [comment]
can you put "uname" into terminal and post what you get from the terminal please?

**Comment by kibner** [comment]
> can you put "uname" into terminal and post what you get from the terminal please?

```
kibner@Kibners-MacBook-Air Adv360-Pro-ZMK % uname
Darwin
```

e: Also, I tested basically undoing the changes in PR #58 and I was able to successfully build the firmware. So, I can definitely confirm that with the OP, too.

**Comment by ReFil** [comment]
Thanks for doing that for me. i'm trying to have it detect the OS and remove those SELinux params appropriately, i'll fiddle a bit more and let you know

**Comment by ReFil** [comment]
Please try it again, the uname command adds a sneaky bit of whitespace in that has to be explicitly removed

**Comment by kibner** [comment]
> Please try it again, the uname command adds a sneaky bit of whitespace in that has to be explicitly removed

It works!

**Comment by ReFil** [comment]
@humblehacker have you had the opportunity to test the changes i've made? it'd be much appreciated if you were able to confirm whether or not they solve the issue

**Comment by humblehacker** [comment]
@ReFil Sorry for the late reply, and thanks for the fix. I checked out your branch and was able to successfully build!
