### ISSUE TITLE
USB logging is enabled by default -- battery life impact?

### ISSUE THREAD

**Issue by elipsitz** [KinesisCorporation/Adv360-Pro-ZMK#98]
It appears that USB logging is enabled by default:

https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V2.0/config/boards/arm/adv360/adv360_left_defconfig#L61-L63
https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V2.0/config/boards/arm/adv360/adv360_right_defconfig#L59-L61

The ZMK docs warn against this, due to an impact on power consumption: https://zmk.dev/docs/development/usb-logging
> Enabling logging increases the power usage of your keyboard, and can have a non-trivial impact to your time on battery. It is recommended to only enable logging when needed, and not leaving it on by default.

Was this left enabled intentionally? Should it be turned off by default to help conserve battery? I've noticed that my keyboard's battery lasts for less time than advertised, and I wonder if this could be partly responsible.

**Comment by ReFil** [comment]
USB logging was left enabled to simplify customer service, allowing for logs to be taken off boards without recompiling firmware. whilst it does have some impact on the battery the lighting features are orders of magnitude more power consuming when enabled, if you're having battery life concerns ensure all lighting is disabled.
